#!/bin/sh
. "$(dirname "$0")/husky.sh"
COMMIT_MSG_FILE="$1"
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

COMMIT_REGEX="^(fix|feat|breakingchange|refactor|test|build):#[0-9]{1,8} .{1,300}$"
# Validar el mensaje
if ! echo "$COMMIT_MSG" | grep -Eq "$COMMIT_REGEX"; then
  echo "❌ Formato de commit inválido."
  echo "   Debe seguir el formato: <type>:#<workItemId> <description>"
  echo "   Ejemplo válido: feat:#123 Nueva funcionalidad"
  echo "   Tipos permitidos: fix, feat, breakingchange, refactor, test, build"
  exit 1
fi
